import Head from "next/head";
import { Inter } from "@next/font/google";
import { Avatar, Grid, Table, Button, Loading } from "@nextui-org/react";

import { Input, Spacer } from "@nextui-org/react";
import { useEffect, useState } from "react";
import axios from "axios";
import { Blocks } from "react-loader-spinner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [todo, settodo] = useState("");
  const [getTodos, setgetTodos] = useState([]);
  const getTasks = async () => {
    try {
      const { data } = await axios.get("http://localhost:3000/api/gettodo");
      setgetTodos(data);
      console.log(getTodos);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getTasks();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center h-screen bg-blue-400 ">
        <div className="flex flex-col justify-center items-center">
          <Input
            onChange={(e) => settodo(e.target.value)}
            label="Add Todo"
            placeholder="Enter Todo"
          />
          <Spacer y={0.5} />
          <Button
            // onPress={handleclick}
            className="bg-blue-500"
          >
            Add
          </Button>
          <Spacer y={0.5} />
          <Table
            className="text-white"
            aria-label="Example table with static content"
            css={{
              backgroundColor: "Blue",
              height: "auto",
              minWidth: "100%",
            }}
          >
            <Table.Header>
              <Table.Column>TO-DO</Table.Column>

              <Table.Column>Actions</Table.Column>
            </Table.Header>
            <Table.Body>
              {getTodos.map(
                (m) => (
                  <Table.Row key={m._id}>
                    <Table.Cell>
                      <span className="text-white">{m.task}</span>
                    </Table.Cell>

                    <Table.Cell>
                      <Grid.Container>
                        <Grid>
                          <Button
                            onPress={() => console.log(m._id)}
                            shadow
                            color="error"
                            auto
                          >
                            Delete{" "}
                          </Button>
                        </Grid>
                      </Grid.Container>
                    </Table.Cell>
                  </Table.Row>
                ),
                <Blocks
                  visible={true}
                  height="80"
                  width="80"
                  ariaLabel="blocks-loading"
                  wrapperStyle={{}}
                  wrapperClass="blocks-wrapper"
                />
              )}
            </Table.Body>
          </Table>
        </div>
      </main>
    </>
  );
}
